# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67a8affbbf39472e3625a65d3448780670b88b5ade1219b44b11608c92fe7d90f1fa6f68ae1b4ee8ab7333303e7574ab580f99ab77662b76433ec0196e4d2de8

test:
  secret_key_base: b36ba6b71a3528731cec2873aada35f68b5ab70d8c00c79cc14fc80d1522914b99e2af1e6af732d6739458099b5cdcb4f4b425b6b267f91ca23b14fd2376675c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
